### ISSUE TITLE
Document python version requirements

### ISSUE THREAD

**Issue by Dobatymo** [sirk390/wxasync#23]
Since the setup files don't have any version requirements, please document that the last version working with python 3.6 is `wxasync==0.45`, and above versions require python 3.7.

I added the version requirement to the setup.py file https://github.com/sirk390/wxasync/pull/24
It doesn't fix it for previous releases though.

**Comment by sirk390** [comment]
Thanks @Dobatymo,
Indead, fixing a warning in python 3.10 and updating to newer best practices (https://github.com/sirk390/wxasync/pull/17 ) caused python 3.6 to be unsupported after wxasync 0.45.
Like you mentioned this is caused by asyncio.run() and asyncio.create_task() now being used instead of asyncio.get_event_loop(), loop.create_task() and loop.run_until_complete().
I think that should be ok if documented.
I'll add the documentation to mention it.
