### ISSUE TITLE
macOS performance issues

### ISSUE THREAD

**Issue by louisnw01** [sirk390/wxasync#28]
Hi Sirk,

Let me start by saying this is a great package, thank you!

I am running into some performance issues on macOS; even at idle, with no widgets, the app.MainLoop seems to suck around 8-10% of CPU constantly. I noticed that you recently made a commit to the main loop, with the comment implying there is no way to idle the main loop on a Mac; am I correct in thinking this is why it uses a lot of CPU at idle? 

I ran the same program with wx's own main loop and was getting around 0.1% of CPU. If you know of any fixes/workarounds, that would be great. Below is an example:
```
import asyncio
import wx
import wxasync


class Frame(wx.Frame):
    def __init__(self):
        super().__init__(None, title='')
        text = wx.StaticText(self)
        text.SetLabel('the quick brown fox jumps over the lazy dog')


async def async_main():
    app = wxasync.WxAsyncApp()
    frame = Frame()
    frame.Show()
    app.SetTopWindow(frame)
    await app.MainLoop()  # After running async MainLoop, 8-10% of CPU is used.


def sync_main():
    app = wx.App()
    frame = Frame()
    frame.Show()
    app.SetTopWindow(frame)
    app.MainLoop()  # After running sync MainLoop, 0.1-0.2% of CPU is used.


if __name__ == '__main__':
    run_type = 'async'
    asyncio.run(async_main()) if run_type == 'async' else sync_main()
```
Thanks!

**Comment by sirk390** [comment]
Hi Louis,

I've done some profiling and ktruss on my MacOS VM. It seems that a lot of time is spent in DispatchTimeout(0) and particularily calling select.kqueue.

There would be the option of reducing the number of times we check for UI events on Mac by increasing the "await asyncio.sleep(0.005)" duration. This will not solve the end issue that DispatchTimeout(0)  is sometimes very slow but could help in the meantime.

Are you able to test with asyncio.sleep(0.02) to see if this improves the performance? 20ms should be more than enough for UI messages (5ms is a bit of an overkill)

I'll to continue to check the Mac EventLoop implementation for a better solution (https://github.com/wxWidgets/wxWidgets/blob/master/src/osx/core/evtloop_cf.cpp). 

See my profiling results:

>>> p.sort_stats("tottime").print_stats(10)
Mon Apr 17 06:32:41 2023    prof

         61352 function calls (60300 primitive calls) in 11.553 seconds

   Ordered by: internal time
   List reduced from 840 to 10 due to restriction <10>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      440    4.727    0.011    4.727    0.011 {method 'control' of 'select.kqueue' objects}
      214    3.286    0.015    3.313    0.015 {built-in method DispatchTimeout}
        1    1.707    1.707    1.732    1.732 {built-in method _BootstrapApp}
    17/14    0.411    0.024    0.418    0.030 {built-in method _imp.create_dynamic}
        1    0.302    0.302    0.302    0.302 {built-in method IsDisplayAvailable}
      439    0.214    0.000    8.713    0.020 /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py:1821(_run_once)
       15    0.191    0.013    0.237    0.016 simple.py:30(update_clock)
        1    0.148    0.148    0.159    0.159 simple.py:8(__init__)
       32    0.052    0.002    0.052    0.002 {built-in method SetLabel}
      214    0.043    0.000    0.043    0.000 {built-in method ProcessIdle}


and ktruss:

  910/0x4af7:  kevent(0x3, 0x0, 0x0)		 = 0 0
  910/0x4af7:  kevent(0x3, 0x0, 0x0)		 = 0 0
  910/0x4af7:  kevent(0x3, 0x0, 0x0)		 = 0 0
  910/0x4af7:  kevent(0x3, 0x0, 0x0)		 = 0 0
  910/0x4af7:  kevent(0x3, 0x0, 0x0)		 = 0 0
  910/0x4af7:  kevent(0x3, 0x0, 0x0)		 = 0 0
  910/0x4af7:  kevent(0x3, 0x0, 0x0)		 = 0 0
  910/0x4af7:  kevent(0x3, 0x0, 0x0)		 = 0 0
  910/0x4af7:  kevent(0x3, 0x0, 0x0)		 = 0 0
  910/0x4af7:  kevent(0x3, 0x0, 0x0)		 = 0 0
  910/0x4af7:  kevent(0x3, 0x0, 0x0)		 = 0 0
  910/0x4af7:  kevent(0x3, 0x0, 0x0)		 = 0 0
  910/0x4af7:  kevent(0x3, 0x0, 0x0)		 = 0 0
  910/0x4af7:  kevent(0x3, 0x0, 0x0)		 = 0 0
  910/0x4af7:  kevent(0x3, 0x0, 0x0)		 = 0 0
  910/0x4af7:  kevent(0x3, 0x0, 0x0)		 = 0 0

**Comment by sirk390** [comment]
Could you try with the latest repo version and :

    app = WxAsyncApp(sleep_duration=0.02)

**Comment by louisnw01** [comment]
Hi Sirk, 

That brings it down to around 1-2%, which is more than acceptable.

In my own profiling I got the same results, with kqueue being right at the top, but I originally thought this was due to extensive use of IO in my program; thanks for clearing that one up.

Have you tried messing with DispatchTimeout's 'timeout' parameter? Don't know if it would do anything but seems like an obvious route to go down. Anyway let me know if you have any success!

Louis

**Comment by sirk390** [comment]
For the history on this topic (as I wrote it only on the wxpython mailing list currently)

I was initially using "Dispatch" (as is done in the example wxWidget code here https://github.com/wxWidgets/Phoenix/blob/master/samples/mainloop/mainloop.py) 

But then we noticed that it caused wx.ProgressDialog to freeze under MacOs. 
Dispatch, under the hood is calling "DispatchTimeout( 1000 )" and then it calls "CFRunLoopRunInMode(kCFRunLoopDefaultMode, timeout / 1000.0 , true);"

This is why I changed it to DispatchTimeout(0), which worked well. 

The value "0" should work well from the apple documentation ( https://developer.apple.com/documentation/corefoundation/1541988-cfrunloopruninmode) that says "If 0, only one pass is made through the run loop before returning; if multiple sources or timers are ready to fire immediately, only one (possibly two if one is a version 0 source) will be fired"

However, I'm still seeing some large durations (like 500ms) in the DispatchTimeout(0) when I was testing it yesterday.
From the documentation I don't think trying passing 10ms would make a difference, but I will give it a try.

**Comment by sirk390** [comment]
I've checked small values like DispatchTimeout(10), but it doesn't make any difference. 

It often takes longer than the timeout, but that might be related to my VM freezing the process. I would be interested in knowing what your values are when you do something like this:
```
                    t = time.time()
                    evtloop.DispatchTimeout(10)
                    t2 = time.time()
                    print ("dispatch", int((t2-t) * 1000))
```
Anyway, I pushed a change to 20ms UI polling by default.  Could you verify that the latest repo version works as expected on MacOS? I will push it to pip if it's ok.

**Comment by louisnw01** [comment]
> I've checked small values like DispatchTimeout(10), but it doesn't make any difference.
> 
> It often takes longer than the timeout, but that might be related to my VM freezing the process. I would be interested in knowing what your values are when you do something like this:
> 
> ```
>                     t = time.time()
>                     evtloop.DispatchTimeout(10)
>                     t2 = time.time()
>                     print ("dispatch", int((t2-t) * 1000))
> ```
> 
> Anyway, I pushed a change to 20ms UI polling by default. Could you verify that the latest repo version works as expected on MacOS? I will push it to pip if it's ok.

Sorry I didn't respond to this; It works, CPU usage falls. However I am using TradingView's lightweight charts, wrapped within my own library which uses the Wx html2 webview. Due to the slower refresh rate, it is noticeably slower and less responsive. 

But this seems to be a MacOS issue rather than a library issue, so i'm okay with it sucking a little bit more CPU for the functionality.

Thanks!

**Comment by sirk390** [comment]
Hi @louisnw01 If needed you can customize for your own needs the "sleep_duration" argument in "WxAsyncApp" (currently 0.02 = 20ms)
